easy_admin:
    entities:
        - App\Entity\Client
        - App\Entity\Project
        - App\Entity\ProjectImage
        - App\Entity\Technology
        - App\Entity\Tag
        - App\Entity\Testimonial
        - App\Entity\BlogPost
        - App\Entity\BlogCategory
        - App\Entity\FAQ
