vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix:         '/uploads/images/projects'
            upload_destination: '%kernel.root_dir%/../public/uploads/images/projects'
